version: '3.9'

services: 
  
  rotten_potatoes_ms_service:
    image: rotten_potatoes_ms_service:1.0
    hostname: rotten_potatoes_ms_service
    build: 
      context: ./rotten-potatoes-ms/src
      dockerfile: Dockerfile
    environment: 
      - MOVIE_SERVICE_URI=movie_service
      - REVIEW_SERVICE_URI=review_service
    networks: 
      - lb_solucao

  movie_service:
    image: movie_service:1.0
    hostname: movie_service
    build: 
      context: ./movie/src/
      dockerfile: Dockerfile
    networks: 
      - lb_solucao

  review_service:
    image: review_service:1.0
    hostname: review_service
    build: 
      context: .
      dockerfile: ./review/src/Dockerfile
    networks: 
      - lb_solucao

networks: 
  lb_solucao:
    driver: bridge