version: '3.9'

services: 
  
  rotten_potatoes_ms_service:
    image: rotten_potatoes_ms_service:1.0
    hostname: rotten_potatoes_ms_service
    build: 
      context: ./rotten-potatoes-ms/src
      dockerfile: Dockerfile
    environment: 
      - MOVIE_SERVICE_URI=movie_service
      - REVIEW_SERVICE_URI=review_service
    networks: 
      - lb_solucao
    ports: 
      - 8066:5000
    depends_on: 
      - pg_db_service
      - movie_service
      - review_service

  movie_service:
    image: movie_service:1.0
    hostname: movie_service
    build: 
      context: ./movie/src/
      dockerfile: Dockerfile
    networks: 
      - lb_solucao
    ports: 
      - 8081:8081

  review_service:
    image: review_service:1.0
    hostname: review_service
    build: 
      context: ./review/src/Review.Web
      dockerfile: Dockerfile
    environment: 
      - ConnectionStrings__MyConnection=Host=pg_db_service;Database=pguser;Username=pguser;Password=Pg@123;
    networks: 
      - lb_solucao
      - db
    ports: 
      - 8282:8282
    depends_on: 
      - pg_db_service

  pg_db_service:
    image: postgres:13.4-alpine
    environment: 
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=Pg@123
    networks: 
      - db

networks: 
  lb_solucao:
    driver: bridge
  db:
    driver: bridge