version: '3.9'

services: 
  
  rotten_potatoes_ms_service:
    image: rotten_potatoes_ms_service:1.0
    hostname: rotten_potatoes_ms_service
    build: 
      context: ./rotten-potatoes-ms/src
      dockerfile: Dockerfile
    environment: 
      - MOVIE_SERVICE_URI=http://movie_service:8181
      - REVIEW_SERVICE_URI=http://review_service:80
    networks: 
      - lb_solucao
    ports: 
      - 8066:5000
    depends_on: 
      - movie_service
      - review_service

  movie_service:
    image: movie_service:1.0
    hostname: movie_service
    build: 
      context: ./movie/src/
      dockerfile: Dockerfile
    environment: 
      - MONGODB_URI=mongodb://mongouser:mongopwd@mongo_db_service:27017/admin
    networks: 
      - lb_solucao
      - app
    depends_on: 
      - mongo_db_service
    restart: always

  review_service:
    image: review_service:1.0
    hostname: review_service
    build: 
      context: ./review/src/Review.Web
      dockerfile: Dockerfile
    environment: 
      - ConnectionStrings__MyConnection=Host=pg_db_service;Database=pguser;Username=pguser;Password=Pg@123;
    networks: 
      - lb_solucao
      - app
    depends_on: 
      - pg_db_service
    restart: always

  pg_db_service:
    image: postgres:13.4-alpine
    environment: 
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=Pg@123
    networks: 
      - app

  mongo_db_service:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
    networks: 
      - app

networks: 
  lb_solucao:
    driver: bridge
  app:
    driver: bridge